apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cvat-redis
  name: cvat-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-redis
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: cvat-redis
    spec:
      containers:
      - image: redis:4.0-alpine
        name: cvat-redis
        resources: {}
      restartPolicy: Always
