apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: cvat-ui
  name: cvat-ui
spec:
  selector:
    matchLabels:
      io.kompose.service: cvat-ui
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: cvat-ui
    spec:
      containers:
      - image: onepanel/cvat-ui:0.17.0_cvat.1.0.0
        name: cvat-ui
        resources: {}
      restartPolicy: Always
