apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cvat-db
    spec:
      containers:
        - name: cvat-db
          image: postgres:10-alpine
          ports:
            - containerPort: 5432
          resources: { }
          volumeMounts:
            - mountPath: /pgdata
              name: cvat-db
          env:
            - name: PGDATA
              value: "/pgdata/data"
            - name: POSTGRES_DB
              value: cvat
            - name: POSTGRES_USER
              value: cvat
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cvat-secrets
                  key: postgres-password
      restartPolicy: Always
      volumes:
      - name: cvat-db
        persistentVolumeClaim:
          claimName: cvat-db
status: {}
