apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cvat-keys
  name: cvat-keys
spec:
  storageClassName: rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
