apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cvat-proxy-claim1
  name: cvat-proxy-claim1
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
